version: "3"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm run dev
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sample_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: django_db
    ports:
      - "5436:5432"
